spring:
  datasource:
    url: "jdbc:postgresql://meduzza.space:5400/tasks"
    password: tasks
    username: tasks
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB